INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140401','LIMA','CAÑETE','SAN VICENTE DE CAÑETE');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140402','LIMA','CAÑETE','CALANGO');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140403','LIMA','CAÑETE','CERRO AZUL');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140404','LIMA','CAÑETE','COAYLLO');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140405','LIMA','CAÑETE','CHILCA');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140406','LIMA','CAÑETE','IMPERIAL');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140407','LIMA','CAÑETE','LUNAHUANA');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140408','LIMA','CAÑETE','MALA');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140409','LIMA','CAÑETE','NUEVO IMPERIAL');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140410','LIMA','CAÑETE','PACARAN');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140411','LIMA','CAÑETE','QUILMANA');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140412','LIMA','CAÑETE','SAN ANTONIO');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140413','LIMA','CAÑETE','SAN LUIS');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140414','LIMA','CAÑETE','SANTA CRUZ DE FLORES');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140415','LIMA','CAÑETE','ZUÑIGA');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140416','LIMA','CAÑETE','ASIA');


INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES	    ('ANIVERSARIO','10','70','2021-12-05','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('PINTADO','10','50','2021-05-11','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('MANTENIMIENTO','9','50','2021-12-14','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('EXCURSION','12','30','2021-12-14','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('MANTENIMIENTO CARPET','10','50','2021-03-16','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('REPARAR CARPETAS','5','50','2021-03-16','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('COMPRAR PODADORAS DE CESPED','5','40','2021-05-20','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('REPARAR COMPUTADORAS','5','70','2021-09-25','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('PROFESOR DE MUSICA','10','30','2021-05-27','ACTIVO');

        
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values ('EDGARD','RODRIGUEZ','Quilmana','edgar124@gmail.com','44248333','960163827','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values         ('LUCAS','CARRANZA','Quilmana','lucas223@gmail.com','40230753','958159127','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('ANTHONY','VELARDE','AntVelar','velarde332@gmail.com','12558199','984821652','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('MARTHA','SANCHEZ','SanMart','martha223@gmail.com','52022189','970456787','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('MATEO','FELIX','MatFelix','mateo223@gmail.com','33842703','946078090','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('FERNANDO','MARTINEZ','Imperial','fernandito@gmail.com','72717476','946078090','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('MARCOS','MEZA','MarcMez','Marco999@gmail.com','12833407','952933352','ADMIN','ACTIVO','2');
        


insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES  ('ANDERSON','HUAMAN','Quilmana','edgar124@gmail.com','12548590','985417252','ALUMNO','ACTIVO','2','3');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES 		('FRANCISCO','PERALTA','Quilmana','edgar124@gmail.com','38726412','962565840','ALUMNO','ACTIVO','2','4');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES 		('JUAN','ALBERDI','Quilmana','JuanP@gmail.com','83923460','960361973','ALUMNO','ACTIVO','2','4');
        
        
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values	('10','9','2021-06-20','2','2');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values	('10','9','2021-06-20','2','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('12','10','2021-06-21','4','3');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','8','2021-06-22','5','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','8','2021-06-22','5','1');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-22','3','5');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-22','6','6');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-22','6','3');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-23','7','2');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-23','3','5');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-23','3','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-24','8','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','10','2021-06-24','2','3');
        
--SELECT * FROM cuotas; CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACTFK
        
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES ('28','10','BROCHA','2021-12-06','2');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES  ('18','9','PINCEL','2021-05-12','2');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('27','14','ESCOBA','2021-12-15','3');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('10','5','CLAVOS','2021-12-16','6');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('10','9','AUTORIZACION','2021-03-17','4');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('5','5','MODULOINTERNET','2021-03-18','8');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('5','5','ASPAS','2021-05-21','7');


