INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140401','Lima','Cañete','San Vicente De Cañete');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140402','Lima','Cañete','Calango');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140403','Lima','Cañete','Cerro Azul');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140404','Lima','Cañete','Coayllo');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140405','Lima','Cañete','Chilca');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140406','Lima','Cañete','Imperial');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140407','Lima','Cañete','Lunahuana');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140408','Lima','Cañete','Mala');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140409','Lima','Cañete','Nuevo Imperial');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140410','Lima','Cañete','Pacaran');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140411','Lima','Cañete','Quilmana');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140412','Lima','Cañete','San Antonio');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140413','Lima','Cañete','San Luis');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140414','Lima','Cañete','Santa Cruz de Flores');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140415','Lima','Cañete','Zuñiga');
INSERT INTO ubigeo(CODUBG,DEPUBG,PROUBG,DISUBG)
VALUES	('140416','Lima','Cañete','Asia');


INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES	    ('Aniversario','10','70','2021-12-05','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Pintado','10','50','2021-05-11','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Mantenimiento','9','50','2021-12-14','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Excursion','12','30','2021-12-14','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Mantenimiento Carpertas','10','50','2021-03-16','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Reparar Carpetas','5','50','2021-03-16','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Compra Podadoras de Cesped','5','40','2021-05-20','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Reparar Computadoras','5','70','2021-09-25','ACTIVO');
INSERT INTO ACTIVIDAD (NOMACT,MONESPACT,CANAPOACT,FECACT,ESTACT) 
VALUES		('Profesor de Musica','10','30','2021-05-27','ACTIVO');

        
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values         ('Edgard','Rodriguez','Quilmana','edgar124@gmail.com','44248333','960163827','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values         ('Lucas','Carranza','Quilmana','lucas223@gmail.com','40230753','958159127','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('Anthony','Velarde','AntVelar','velarde332@gmail.com','12558199','984821652','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('Martha','Sanchez','SanMart','martha223@gmail.com','52022189','970456787','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('Mateo','Felix','MatFelix','mateo223@gmail.com','33842703','946078090','APODERADO','ACTIVO','2');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('Fernando','Martinez','Imperial','fernandito@gmail.com','72717476','946078090','APODERADO','ACTIVO','1');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG)
 values 		('Maros','Meza','MarcMez','Marco999@gmail.com','12833407','952933352','ADMIN','ACTIVO','2');
        


insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES  ('Anderson','Huaman','Quilmana','edgar124@gmail.com','12548590','985417252','ALUMNO','ACTIVO','2','3');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES 		('Francisco','Peralta','Quilmana','edgar124@gmail.com','38726412','962565840','ALUMNO','ACTIVO','2','4');
insert into PERSONA (NOMPER, APEPER, PASPER, EMAPER, DNIPER, CELPER, ROLPER, ESTPER,IDUBG,PERSONA_IDPER)
VALUES 		('Juan','Alberdi','Quilmana','JuanP@gmail.com','83923460','960361973','ALUMNO','ACTIVO','2','4');
        
        
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values	('10','9','2021-06-20','2','2');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values	('10','9','2021-06-20','2','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('12','10','2021-06-21','4','3');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','8','2021-06-22','5','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','8','2021-06-22','5','1');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-22','3','5');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-22','6','6');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-22','6','3');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-23','7','2');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-23','3','5');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('9','9','2021-06-23','3','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('5','5','2021-06-24','8','4');
insert into CUOTA (CANCUOT,MONCUOT,FECCUOT,IDACT,IDPER) 
values		('10','10','2021-06-24','2','3');
        
--SELECT * FROM cuotas; CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACTFK
        
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES ('28','10','Brocha','2021-12-06','2');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES  ('18','9','Pincel','2021-05-12','2');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('27','14','Escoba','2021-12-15','3');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('10','5','Clavos','2021-12-16','6');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('10','9','Autorizacion','2021-03-17','4');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('5','5','Modulo Internet','2021-03-18','8');
INSERT INTO GASTO_ACTIVIDAD (CANGASACT,MONGASACT,DESGASACT,FECGASACT,IDACT) 
VALUES	   ('5','5','Aspas','2021-05-21','7');


