CREATE DATABASE DBEDUCASI;
USE DBEDUCASI;

CREATE TABLE ACTIVIDAD (
    IDACT int  NOT NULL IDENTITY(1,1),
    NOMACT varchar(60)  NOT NULL,
    MONESPACT int  NOT NULL,
    CANAPOACT int  NOT NULL,
    FECACT date  NOT NULL,
    ESTACT char(1)  NOT NULL,
    ESTFINACT char(1)  NOT NULL,
    CONSTRAINT ACTIVIDAD_pk PRIMARY KEY  (IDACT)
);

-- Table: CRONOGRAMAS_COMUNICADOS
CREATE TABLE CRONOGRAMAS_COMUNICADOS (
    IDCRON int  NOT NULL IDENTITY(1,1),
    IMACRO binary(700)  NOT NULL,
    CONSTRAINT CRONOGRAMAS_COMUNICADOS_pk PRIMARY KEY  (IDCRON)
);

-- Table: CUOTA
CREATE TABLE CUOTA (
    IDCUOT int  NOT NULL IDENTITY(1,1),
    CANCUOT int  NOT NULL,
    MONCUOT int  NOT NULL,
    ESTCUOT char(1)  NOT NULL,
    FECCUOT date  NOT NULL,
    IDACT int  NOT NULL,
    IDPER int  NOT NULL,
    CONSTRAINT CUOTA_pk PRIMARY KEY  (IDCUOT)
);

-- Table: GASTO_ACTIVIDAD
CREATE TABLE GASTO_ACTIVIDAD (
    IDGASACT int  NOT NULL IDENTITY(1,1),
    DESGASACT varchar(60)  NOT NULL,
    GASACT int  NOT NULL,
    FECGASACT date  NOT NULL,
    ESTGASACT char(1)  NOT NULL,
    IDACT int  NOT NULL,
    CONSTRAINT GASTO_ACTIVIDAD_pk PRIMARY KEY  (IDGASACT)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    IDPER int  NOT NULL IDENTITY(1,1),
    NOMPER varchar(20)  NOT NULL,
    APEPER varchar(20)  NOT NULL,
    PASPER varchar(16)  NOT NULL,
    EMAPER varchar(20)  NOT NULL,
    DIREPER varchar(20)  NOT NULL,
    DNIPER char(8)  NOT NULL,
    CELPER char(9)  NOT NULL,
    ROLPER char(1)  NOT NULL,
    ESTPER char(1)  NOT NULL,
    PERSONA_IDPER int  NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY  (IDPER)
);

-- foreign keys
-- Reference: CUOTA_ACTIVIDAD (table: CUOTA)
ALTER TABLE CUOTA ADD CONSTRAINT CUOTA_ACTIVIDAD
    FOREIGN KEY (IDACT)
    REFERENCES ACTIVIDAD (IDACT);

-- Reference: CUOTA_PERSONA (table: CUOTA)
ALTER TABLE CUOTA ADD CONSTRAINT CUOTA_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER);

-- Reference: PERSONA_PERSONA (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PERSONA
    FOREIGN KEY (PERSONA_IDPER)
    REFERENCES PERSONA (IDPER);

-- Reference: SALDO_ACTIVIDAD_ACTIVIDAD (table: GASTO_ACTIVIDAD)
ALTER TABLE GASTO_ACTIVIDAD ADD CONSTRAINT SALDO_ACTIVIDAD_ACTIVIDAD
    FOREIGN KEY (IDACT)
    REFERENCES ACTIVIDAD (IDACT);

insert into PERSONA (NOMPER,APEPER,PASPER,EMAPER,DIREPER,DNIPER,CELPER,ROLPER,ESTPER,PERSONA_IDPER) VALUES 
('EDGARD','SANCHEZ','ASSDDF','DSDSDF@GMAIL.COM','JR. PUNO','72747534','934567213','A','I',null);

select * from PERSONA;